### ISSUE TITLE
Placeholder text not working

### ISSUE THREAD

**Issue by theme1256** [hexxu-dev/UFormKit#1]
Hi

I can't get placeholder text working.  
This might be a skill issue on my part.

**Comment by hexxu-dev** [comment]
Hello!

You can add a placeholder like this:
[text your-subject placeholder "Contact"]

Can you please paste the code snippet you tried to apply, so we can check if it is correct?

**Comment by theme1256** [comment]
Was unsure of the order and the syntax, because the other attributes use a collon.
It works fine, when I add you sample at the end of my code.
